sudo: false
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
notifications:
  email: true
before_script:
  - npm prune --production
  - npm install
script:
  - npm i -g now@canary
  - npm run test
after_success:
   - now dev -e --token=$NOW_TOKEN 