sudo: false
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune --production
  - npm install
script:
  - npm i -g now@canary
  - npm run test
after_success:
   - now --public --token=$NOW_TOKEN 
   - now secrets ls --token=$NOW_TOKEN 