sudo: false
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm install
script:
  - npm i -g now
  - npm run test
  - ls -a 
after_success:
   - now --public --token=$NOW_TOKEN 
  