sudo: false
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
notifications:
  email: true
before_script:
  - npm prune --production
  - npm install
script:
  - npm i -g now@13.0.4
  - npm run test
after_success:
   - now --token=$NOW_TOKEN --public 